# GoReleaser configuration for container-use
version: 2

project_name: container-use

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/man.sh

builds:
  - id: container-use
    binary: container-use
    main: ./cmd/container-use
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: container-use-archive
    ids:
      - container-use
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - completions/*
      - man/*

homebrew_casks:
  - repository:
      owner: "{{ .Env.GH_ORG_NAME }}"
      name: homebrew-tap
      branch: "{{ .ProjectName }}-{{ .Version }}"
      token: "{{ .Env.GITHUB_TOKEN }}"
      pull_request:
        enabled: true
    name: container-use
    binary: container-use
    skip_upload: auto # if the version is like v0.0.0-rc1, don't make the tap PR.
    commit_author:
      name: container-use-bot
      email: noreply@dagger.io
    url:
      template: "https://github.com/{{ .Env.GH_ORG_NAME }}/container-use/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/{{ .Env.GH_ORG_NAME }}/container-use"
    description: "Containerized environments for coding agents"
    manpages:
      - man/container-use.1
    completions:
      bash: "completions/container-use.bash"
      zsh: "completions/container-use.zsh"
      fish: "completions/container-use.fish"
    hooks:
      post:
        install: |
          # remove quarantine xattr (note we don't do anything with signatures yet)
          if File.exist?("/usr/bin/xattr")
            system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/container-use"
          end

          # Create cu symlink for backward compatibility
          FileUtils.ln_sf "#{HOMEBREW_PREFIX}/bin/container-use", "#{HOMEBREW_PREFIX}/bin/cu"

          # Install cu completions for backward compatibility
          bash_completion = "#{HOMEBREW_PREFIX}/etc/bash_completion.d"
          zsh_completion = "#{HOMEBREW_PREFIX}/share/zsh/site-functions"
          fish_completion = "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"

          if File.exist?("#{staged_path}/completions/cu.bash")
            FileUtils.mkdir_p bash_completion
            FileUtils.cp "#{staged_path}/completions/cu.bash", "#{bash_completion}/cu"
          end

          if File.exist?("#{staged_path}/completions/cu.zsh")
            FileUtils.mkdir_p zsh_completion
            FileUtils.cp "#{staged_path}/completions/cu.zsh", "#{zsh_completion}/_cu"
          end

          if File.exist?("#{staged_path}/completions/cu.fish")
            FileUtils.mkdir_p fish_completion
            FileUtils.cp "#{staged_path}/completions/cu.fish", "#{fish_completion}/cu.fish"
          end
        uninstall: |
          # Remove cu symlink
          FileUtils.rm_f "#{HOMEBREW_PREFIX}/bin/cu"

          # Remove cu completions
          FileUtils.rm_f "#{HOMEBREW_PREFIX}/etc/bash_completion.d/cu"
          FileUtils.rm_f "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_cu"
          FileUtils.rm_f "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/cu.fish"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: "{{ .Env.GH_ORG_NAME }}" # reconfigure if test releasing on your own fork
    name: container-use
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## container-use {{ .Tag }}

    Download the pre-compiled binaries from the assets below.
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.GH_ORG_NAME }}/container-use/compare/{{ .PreviousTag }}...{{ .Tag }}
